added error in flow yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -36,6 +36,29 @@ jobs:
         pip install --upgrade pip
         pip install -r requirements.txt
 
+    - name: Download and extract data file
+      run: |
+        # Try to download the file
+        FILE_URL="https://archives.nseindia.com/content/cm/BhavCopy_NSE_CM_0_0_0_${{ steps.current-time.outputs.formattedTime }}_F_0000.csv.zip"
+        FILE_PATH="data/BhavCopy_${{ steps.current-time.outputs.formattedTime }}.zip"
+        
+        echo "Attempting to download file: $FILE_URL"
+
+        # Download the file and check if the download is successful
+        curl --fail --silent --show-error --output $FILE_PATH $FILE_URL
+        if [ $? -ne 0 ]; then
+          echo "Error downloading and extracting the file for ${{ steps.current-time.outputs.formattedTime }}. Skipping the update."
+          exit 0  # Exit gracefully without failing the whole workflow
+        fi
+
+        # Extract the downloaded zip file
+        unzip -o $FILE_PATH -d data/
+        if [ $? -ne 0 ]; then
+          echo "Error extracting the file for ${{ steps.current-time.outputs.formattedTime }}."
+          exit 0  # Exit gracefully if extraction fails
+        fi
+      continue-on-error: true  # Don't stop the workflow on errors here
+
     - name: Run data update script
       run: |
         python3 get_todays_date.py
